### ISSUE TITLE
提供设置代理功能

### ISSUE THREAD

**Issue by kaixinol** [Night-stars-1/LiteLoaderQQNT-Plugin-Plugin-Store#1]

**Comment by LanYunDev** [comment]
+1
在QQ配置代理的情况下,发送下面报错.望解决.
Error: connect EBADF xxx:443
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)

**Comment by Night-stars-1** [comment]
![image](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-Plugin-Store/assets/99261160/5991fedb-fe3d-4afc-ad25-0333fe412ccc)
这是不设置代理的更新情况，我非常不解为什么不设置代理可以正常更新的情况下要去设置代理
